### ISSUE TITLE
react 16 has no exported member CSSWideKeyword

### ISSUE THREAD

**Issue by tsiq-swyx** [alexkatz/react-tiny-popover#11]
getting this error: `
node_modules/react-tiny-popover/dist/index.d.ts(55,24): error TS2694: Namespace 'React' has no exported member 'CSSWideKeyword'.`

my investigation concludes that they removed CSSWideKeyword after react 15: https://github.com/DefinitelyTyped/DefinitelyTyped/search?utf8=%E2%9C%93&q=CSSWideKeyword&type=

this may be a related issue on their repo: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20743

I don't know if this can be solved.. but just reporting it.

great library other wise!

**Comment by hir06** [comment]
I am still facing this issue with react:  16.13.0 and typescript: 3.9.5 combination
