### ISSUE TITLE
Improvement - Popover div only is animated using opacity

### ISSUE THREAD

**Issue by juan-bastidas** [alexkatz/react-tiny-popover#12]
This is a great component but:

One of the most interesting things is that you can make it a modal or a div, that is my case I'm transforming it to be a slide in panel (bottom to top) when agent is a mobile device, sometimes the popover in mobile devices is difficult to handle, so I wonder if it is possible to add desired transition via configuration when the popover appears so in this case I can slide it in instead of the default fade in.

Also I have notice browser become a bit slow, thing in browser console sometimes are slow, like when you use arrows to navigate console history and I thing is maybe cause of this component, maybe setInterval fault.

Thanks

**Comment by alexkatz** [comment]
Opacity animation has been removed from the library, and instead I recommend creating custom enter and leave animations using your preferred library or css!

**Comment by julioflima** [comment]
@alexkatz still no examples... Please...
