### ISSUE TITLE
`onClickOutside` isn't fired when clicking react-native buttons (Button, Pressable, etc).

### ISSUE THREAD

**Issue by kirbyfu** [alexkatz/react-tiny-popover#137]
I'm currently hiding a popover when the user clicks outside by using `onClickOutside`. This generally works but when clicking other react-native buttons, `onClickOutside` isn't triggered (react native buttons stops propagation to [prevent click bubbling](https://github.com/necolas/react-native-web/issues/2115#issue-982750446)).

Would changing this [line](https://github.com/alexkatz/react-tiny-popover/blob/5b64d8e91613d29fe70b39b08b569c09539c103e/src/Popover.tsx#L194) to listen to the capture phase be reasonable?
```js
window.addEventListener('click', handleOnClickOutside, true);
```

Or perhaps adding `onClickOutsideCapture` if backwards compatibility is an issue.

Sandbox example showing issue: https://codesandbox.io/s/musing-tharp-tjo25?file=/src/App.js

**Comment by carlostpg** [comment]
It appears this suggestion was incorporated at some point. 

https://github.com/alexkatz/react-tiny-popover/blob/master/src/Popover.tsx#L183

Use `clickOutsideCapture` to control "the useCapture option passed along as the third argument to the internal window.addEventListener used by onClickOutside."

**Comment by alexkatz** [comment]
@carlostpg You are correct. This prop is included in the docs as well. My apologies for leaving this issue open.  I'll close this issue for now!
