### ISSUE TITLE
Could the Popover be controlled by a click event?

### ISSUE THREAD

**Issue by baba43** [alexkatz/react-tiny-popover#149]
I would like to add a button with popover to a [Fullcallender](https://github.com/fullcalendar/fullcalendar). 

Fullcalendar provides [a simple mechanism](https://fullcalendar.io/docs/customButtons) for adding buttons in general:

    myCustomButton: {
      text: 'custom!',
      click: function(clickEvent, buttonElement) {
        alert('clicked the custom button!');
      }
    }

Sadly, this way we can only provide `onClick` handlers but no HTML and also no React components.

That is why I'd like to ask if and how I might integrate `react-tiny-popover` in a situation like this?

**Comment by afraser** [comment]
this library is built on react so it probably doesn't make sense for your use case unless you plan on adopting react as well

**Comment by alexkatz** [comment]
It looks like FullCallendar supports [JSX content injection](https://fullcalendar.io/docs/react#content-injection), which should allow you to use `react-tiny-popover` normally. If you try this out and experience some difficulty, feel free to reopen this issue. Thanks!
