### ISSUE TITLE
'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by narendra-sharma** [alexkatz/react-tiny-popover#156]
Cdn Error at:
 https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/js/src/dropdown.js

Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

**Comment by alexkatz** [comment]
This library has nothing to do with Bootstrap dropdowns. Closing this issue.
