### ISSUE TITLE
Min width of content based on control width

### ISSUE THREAD

**Issue by alexeybondarenko** [alexkatz/react-tiny-popover#16]
Hi! First of all thanks for this package. I think it's the best package for popovers. It has the only generic logic of positioning and this is great. I'm using it in Tooltips, Dropdown, Selects, Datepickers and other components. 

For example, I've found a way to use it in new react-select v2. If you are interesting I can share a code. 

In some interfaces I need to control the width of content depends on target element size. e.g. min-width of menu list in select has to be not thinner than control width. 

do you have an idea how it can be done with tiny popover?

**Comment by alexkatz** [comment]
Thanks for your kind words! Indeed, I am interested in how you’re using the popover with react-select. I’d love to see your code, if that’s cool.  

Can you clarify what you mean about width? One suggestion I have is perhaps the Autosize component from the react-virtualized library, which you’d use as a parent that will inject width and height into its child. But I’m still not quite sure I understand your question fully. 

Best,
Alex

**Comment by alexeybondarenko** [comment]
Hi, Alex! It works fine with react-select, and I've already found an answer to my question) I will show you a code. It's not ideal, looks like a hack, but it allows us to fix the bug with scroll and other bugs of react-select.

It's the customization of SelectContainer component. Also you can that I'm controling the size of menu for bottom, top positioning.

```
import React from 'react';
import { components } from 'react-select';
import { compose, setDisplayName } from 'recompose';

import Popover from '@/components/Popover';

const isMenuChild = index => index === 2;
const SelectContainer = ({ children, ...rest }) => {
  const menu = children.filter((child, index) => isMenuChild(index));
  const restChildren = children.filter((child, index) => !isMenuChild(index));
  return (
    <Popover
      position={['bottom', 'top']}
      align={'left'}
      isOpen={rest.selectProps.menuIsOpen}
      onClickOutside={rest.selectProps.onBlur}
      content={({ position, targetRect }) => {
        const style = {};
        if (['top', 'bottom'].indexOf(position) > -1) {
          style.width = `${targetRect.width}px`;
        }

        return (
          <div style={style}>
            { menu }
          </div>
        );
      }}
    >
      <components.SelectContainer {...rest}>
        {restChildren}
      </components.SelectContainer>
    </Popover>
  );
};

export default compose(setDisplayName('SelectContainer'))(SelectContainer);
```

For this case, it would be nice to disable right and left positioning of the popover. But anyway, now it also works fine)
