### ISSUE TITLE
Question: is this library still maintained?

### ISSUE THREAD

**Issue by felpsio** [alexkatz/react-tiny-popover#163]
Looks like there are 9 months since the last commit. The library still has some bugs and a good amount of issues and PRs.

I wonder if we should move to another package.

Does anyone know if the author still plans to support this library or any other good substitute?

**Comment by alexkatz** [comment]
Hi, maintainer here! As long as I am using this library in my own projects (I still very much am), I will continue maintaining this library!

I do admit though, that I sometimes let months lapse, as you've noticed.
