### ISSUE TITLE
Popover appears at top left of the screen

### ISSUE THREAD

**Issue by Vaasu-Dhand** [alexkatz/react-tiny-popover#177]
I am using the popover component straight from the readme. But, it always appears at the top left of the document like so. I am not sure why that is the case. I have a wrapper over the component which has the following markup:

```javascript
export const EventPopover = React.forwardRef(({ isPopoverOpen, setIsPopoverOpen, handleModifySchema }, ref) => {
  // const [isPopoverOpen, setIsPopoverOpen] = useState(true);

  console.log(ref);

  const renderBody = useCallback((contentProps) => {
    console.log(contentProps);
    return <PopoverBody>This is my popover</PopoverBody>;
  }, []);

  return (
    <Popover
      isOpen={isPopoverOpen}
      positions={['left']} // if you'd like, you can limit the positions
      padding={10} // adjust padding here!
      reposition={false} // prevents automatic readjustment of content position that keeps your popover content within its parent's bounds
      onClickOutside={() => setIsPopoverOpen(false)} // handle click events outside of the popover/target here!
      content={renderBody}
      // parentElement={ref}
    >
      <>This</>
    </Popover>
  );
});
```

One more thing, I noticed, unlike other popovers. There is no `transform: translate` property in the `react-tiny-popover-container` element. 
<img width="255" alt="image" src="https://user-images.githubusercontent.com/64599364/198191615-a959e15e-b03a-40c8-92fe-acced5bc3f2b.png">

<img width="318" alt="image" src="https://user-images.githubusercontent.com/64599364/198191257-c4c179f6-24a9-4a42-9166-874cd3086cf7.png">

**Comment by Vaasu-Dhand** [comment]
@alexkatz Can you take a look at this?

**Comment by wilkinsonjack1993** [comment]
@Vaasu-Dhand I had the same problem. What caused mine is that I have my own button component as the popover child.

```
<Popover
      ...
    >
      <MyButtonComponent />
</Popover>
```

Changing this to be wrapped in a div component fixed it:
```
<Popover
      ...
    >
      <div>
        <MyButtonComponent />
      </div>
</Popover>
```

Its an annoying work around and I haven't looked into the code so can't tell you why it is happening but maybe changing:
`<>This</>` to `<div>This</div>` will unblock you 👍

**Comment by alexkatz** [comment]
@Vaasu-Dhand @wilkinsonjack1993 The child you supply `react-tiny-popover` with needs to support `ref`.

Check out [React's ref forwarding docs](https://reactjs.org/docs/forwarding-refs.html).

In short, A `div` element supports `ref`, but a fragment won't, nor will a custom component that does not use `forwardRef` internally.
