### ISSUE TITLE
React 16 Portals support

### ISSUE THREAD

**Issue by dbergey** [alexkatz/react-tiny-popover#18]
Hi there!

What needs to happen for React 16 Portals to be supported? Is that something someone could take on and submit a PR for? The `portal-progress` branch seems to be behind master, but might be what is shipped on NPM?

**Comment by alexkatz** [comment]
Hi! Yeah, I’d gotten started on a Portals implementation in the portal-progress branch, but haven’t really had the time to continue it lately. It’s certainly something someone could take on and submit a PR for!

**Comment by Scoutski** [comment]
I know this is a late reply but would love to see portals used (esp in place unstable_renderSubtreeIntoContainer). I may be able to work on this a bit, but just wanted to know what the status of the portal-progress branch was?
