### ISSUE TITLE
Nested popovers

### ISSUE THREAD

**Issue by baleeds** [alexkatz/react-tiny-popover#19]
I'm having trouble using Popovers inside of each other.

Here is the code:
```
<Popover
  isOpen={showMore}
  disableReposition
  onClickOutside={() => this.setState({ showMore: false, showActiveDetails: false })}
  content={(
    <Flyout>
      <Popover
        isOpen={showActiveDetails}
        disableReposition
        onClickOutside={() => this.setState({ showMore: false, showActiveDetails: false })}
        content={(
          <Flyout>Other stuff</Flyout>
        )}
      >
        <FlyoutOption onClick={() => this.setState({ showActiveDetails: true })}>
          Show active details
        </FlyoutOption>
      </Popover>
      <FlyoutOption>
        Other stuff
      </FlyoutOption>
    </Flyout>
  )}
>
  <button
    onClick={() => this.setState({ showMore: true })}
  >
    Open
  </button>
</Popover>
```

**Expected behavior:** Clicking the open button shows the parent popover, then clicking on 'show active details' opens another popover.  Clicking outside the inner popover (in the parent), would hide the inner.  Clicking outside the parent would hide both.

**Actual behavior:** Opening parent and child works well.  Clicking parent doesn't hide child.  Clicking outside both hides the parent, breaks the child, and prevents either from opening again.

**Observations:** It looks like the child isn't being unmounted when the parent is unmounted.

**Comment by jakelheknight** [comment]
I have issues with this as well.

**Comment by JonathanKolnik** [comment]
+1

**Comment by Sauco82** [comment]
+1

**Comment by crowmw** [comment]
+1
