### ISSUE TITLE
DOMRect is not defined

### ISSUE THREAD

**Issue by marcelo-mason** [alexkatz/react-tiny-popover#198]
Getting this error w/ v8.0.0 on Nextjs

 ⨯ node_modules/react-tiny-popover/dist/util.js (4:18) @ eval
 ⨯ ReferenceError: DOMRect is not defined

**Comment by alexkatz** [comment]
Yeah, realized SSR is broken. Pushing a fix for this shortly, hang tight.

**Comment by alexkatz** [comment]
`8.0.2` has been released and has resolved all SSR issues!
