### ISSUE TITLE
'Popover' cannot be used as a JSX component

### ISSUE THREAD

**Issue by singpolyma** [alexkatz/react-tiny-popover#204]
`Its return type 'ReactNode' is not a valid JSX element.`

I get this after upgrading to the latest version of the library.

**Comment by nikasakandelidze** [comment]
same for me

**Comment by cristian-sima** [comment]
same here

**Comment by dcorbin** [comment]
I continue to have this problem even with typescript 5.6.3

**Comment by alexkatz** [comment]
Sounds like an issue in the resolution of React's type dependencies. If you go to definition on anything you import from react-tiny-popover, do you see a different version of React's types used when compared to your local project's React types version?

**Comment by dcorbin** [comment]
I'm not sure I fully understand what you are asking.  The only place I import react-tiny-popover is already in my local project.

One point of confusing is that react-tiny-popover is 8.1.3, but looking the repository here the latest release is 7.x

**Comment by alexkatz** [comment]
I was able to [reproduce the problem](https://codesandbox.io/p/sandbox/kkpwcd), and have [pushed a fix](https://github.com/alexkatz/react-tiny-popover/commit/0420ef57d368120bd09b8e45a5720daeaa3189fd).

If you upgrade react-tiny-popover to newly published version 8.1.4 on npm, it should be resolved.

I'll close this issue for now, but please let me know if you experience further issues with this.
