### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jose-pleonasm** [alexkatz/react-tiny-popover#25]
Hi, I've created an [pull request](https://github.com/alexkatz/react-tiny-popover/pull/24) to fix [React error #170](https://reactjs.org/docs/error-decoder.html/?invariant=170) and you've merged it. Thanks for that! Are you going to publish new release with this patch?

**Comment by alexkatz** [comment]
I have! Sorry for not getting around to this earlier. Thanks!
