### ISSUE TITLE
Popover isn't work in IE11 even after polyfill everything

### ISSUE THREAD

**Issue by iJoyCode** [alexkatz/react-tiny-popover#3]
Popover isn't work in IE11 even after polyfill everything

**Comment by iJoyCode** [comment]
@alexkatz Hello, I've created an pull request to fix IE11 compatibility. Could you please take a look?
https://github.com/alexkatz/react-tiny-popover/pull/4

**Comment by alexkatz** [comment]
Looks good. Fixed the generics with the arrayUnique function a bit before merging.

Fixed, pushed, and published! Thanks! :)
