### ISSUE TITLE
Add onMoveOutside function

### ISSUE THREAD

**Issue by jevgenimarenkov** [alexkatz/react-tiny-popover#32]
We are opening the popover onMouseOver but we would like to close it also after the mouse has moved out of the popover. 

There is an event function onClickOutside provided but there is no function onMouseOutside (when the mouse has moved out of the popover). 

Would be a useful feature to have! Would it be worth implementing?

**Comment by alexkatz** [comment]
I like this idea! I'll try and get around to it soon, or feel free to submit a PR if you'd like! Cheers.
