### ISSUE TITLE
Adjust nudgeLeft and nudgeTop according to container div not body

### ISSUE THREAD

**Issue by vishal-akg** [alexkatz/react-tiny-popover#33]
I want to constrain the popover content within container div, adjust nudgetLeft  and nudgeTop according to div.
I have gone throught documentation and found option of using **contentDestination**  but that is not working for me, throwing error cannot read remove of null on passing ref to this option.

If i am doing something wrong please provide some working example using this example.
Demo provided in read.me is also not showing popover in orange box.

**Comment by Julious1994** [comment]
@vishal-akg I added pull request for that problem.
Once changes will approve it'll added to repo.
Till that you can use this https://github.com/Julious1994/react-tiny-popover repo if you wish.

Thank you

**Comment by meikidd** [comment]
I am facing this issue too, @alexkatz could you publish a new version for this fix? Thanks a lot.

**Comment by tonix-tuft** [comment]
I am sorry guys, I don't know if this is the right place to ask this question, but could someone of you provide an example on how to use `contentDestination`? I would like to reference the parent div of the popover:

```
render() {
      return (
                <div> // <--- I need to render it within this div and not document.body...
                       <Popover
                             contentLocation={???}
                             // ...
                       />
                </div>
      )
}
```

Do I need to use a `ref` and trigger a rerender with `setState` in `componentDidMount()` , or is there an easier method provided by the component itself?
