### ISSUE TITLE
Popovers with redux

### ISSUE THREAD

**Issue by OArnarsson** [alexkatz/react-tiny-popover#35]
Hey, I just wanted to check if there was any kind of support for redux integration?
So far the popover content is rendered outside the "App" so the provider does not wrap the popover, making redux integration more difficult.

Has anyone found a good way of combining the two so far?

**Comment by dardino** [comment]
I have the same issue but with ThemeContext.Consumer

**Comment by jdgarcia** [comment]
Just ran into the same issue today and we got around with by wrapping the content in a new Provider. Since we use a popover in more than place I made a wrapper component.

```tsx
import React from 'react';
import Popover from 'react-tiny-popover';
import { Provider } from 'react-redux';
import store from '../redux/store';

type ConnectedPopoverProps = React.ComponentPropsWithoutRef<typeof Popover>;

const ConnectedPopover: React.FC<ConnectedPopoverProps> = props => (
  <Popover
    {...props}
    content={contentProps => (
      <Provider store={store}>
        {typeof props.content === 'function'
          ? props.content(contentProps)
          : props.content
        }
      </Provider>
    )}
  />
);

export default ConnectedPopover;
```

**Comment by OArnarsson** [comment]
This can be solved by simply wrapping the parent of the PopOver container in the provider, sorry for the confusion.
