### ISSUE TITLE
Migrate off componentWillMount

### ISSUE THREAD

**Issue by probablyup** [alexkatz/react-tiny-popover#37]
With the [release of React 16.9](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html) they're now actively warning against usage.

**Comment by GuillaumeCisco** [comment]
any updates on this?
I've just created a PR: https://github.com/alexkatz/react-tiny-popover/pull/44
How could I test this?

**Comment by DaveTorbeck** [comment]
@alexkatz Is it possible to get this merged?

**Comment by alexkatz** [comment]
No longer used!
