### ISSUE TITLE
How to retain the rendered popover in the DOM after closing it?

### ISSUE THREAD

**Issue by tonix-tuft** [alexkatz/react-tiny-popover#38]
If I render a popover with `isOpen: true`  and close it afterwards with `isOpen: false`, the popover is removed from the DOM.

Is there a way to tell `react-tiny-popover` to retain the already rendered popover in the DOM, without removing it? I basically need to just hide the popover.

This would be useful especially if the component inside of the popover is rendered progressively (think of an infinite scroll containing the notifications of a user). If the component is heavy, reopening the popover after closing leads to some seconds of waiting before seeing the popover again.

**Comment by kiruh** [comment]
```
import React, { useState } from "react";
import { Popover } from "react-tiny-popover";

const App = () => {
  const [isOpen, setIsOpen] = useState(false);

  const contentStyle = {};
  if (!isOpen) contentStyle.display = "none";

  return (
    <Popover isOpen content={<div style={contentStyle}>Content</div>}>
      <button onClick={() => setIsOpen((value) => !value)}>Open</button>
    </Popover>
  );
};

```

**Comment by alexkatz** [comment]
@kiruh Thanks for the example. I think this is the most straightforward way to obtain this functionality. Keep the popover open, and adjust the display/visibility/opacity of the popover element.
