### ISSUE TITLE
Currently no way to apply styles using scss variables to arrow color

### ISSUE THREAD

**Issue by czieglerAC** [alexkatz/react-tiny-popover#46]
Because the ArrowContainer seems to handle its own styling, and there is no good way to get scss variables from your typescript file, it is difficult to match the styling from the popover itself to the arrowcontainer if your popover is getting its color from a scss variable. I have currently resorted to hard-coding the hex value of my variable into my typescript file. It would be great if there was some way to set the styling for the arrowContainer using a class.

**Comment by alexkatz** [comment]
Hi, a `className` prop has since been added to `ArrowContainer`!
