### ISSUE TITLE
Using strict mode gives warning about deprecated findDOMNode usage

### ISSUE THREAD

**Issue by makker** [alexkatz/react-tiny-popover#50]
To activate strict mode add StrictMode element to ReactDOM rendered like this: 
```javascript
ReactDOM.render(
  <React.StrictMode>
    <Root store={store} />
  </React.StrictMode>,
  document.getElementById('root')
);
```

Then react-tiny-popover gives this warning in the browser:

>  Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Popover which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

The Popover.tsx uses deprecated findDOMNode function in componentDidMount and componentDidUpdate. These should be refactored to use ref instead.

Here's more info about the issue:
* https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage
* https://medium.com/trabe/getting-rid-of-finddomnode-method-in-your-react-application-a0d7093b2660

**Comment by alexkatz** [comment]
Version 4.1 addresses this, and findDOMNode is no longer used. 

Cheers.
