### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by Abdubek** [alexkatz/react-tiny-popover#53]
I have a warning: findDOMNode was passed an instance of Popover which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

How critical is this?

**Comment by HeikkiMoilanen** [comment]
Hello!

I am also getting this warning from using react-tiny-popover in strict mode:

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Popover which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

Even if it's just a deprecation warning, it's cluttering the javascript console and makes actually meaningful warnings harder to spot. Would be awesome if it could be fixed :).

**Comment by mika-kaki** [comment]
I am also looking forward for a fix for this. Thanks for your great work!

**Comment by neoncube2** [comment]
This looks like a duplicate of https://github.com/alexkatz/react-tiny-popover/issues/50

**Comment by alexkatz** [comment]
findDOMNode has been removed in version 4.1!

**Comment by mika-kaki** [comment]
Awesome, thanks!
