### ISSUE TITLE
Any way to reposition popover

### ISSUE THREAD

**Issue by crowmw** [alexkatz/react-tiny-popover#59]
I display a 200px height popover. Due to a change in the number of displayed items, the popover reduces the height to 100px. Unfortunately it doesn't change its position at the same time, so it starts to levitate somewhere above the element to which it was attached. After using mouse scroll  it comes back to right place. 

Is there any possibility to manually recalculate the position of the popover?

**Comment by crowmw** [comment]
My solution for this right now:

in useEffect when change number of displayed items:
```
    if (isOpen) {
      const element = document.querySelector('.scrollable-container')
      element.scrollBy(0, 1)
      setTimeout(() => {
        element.scrollBy(0, -1)
      }, 100)
    }
```

**Comment by zhaoyao91** [comment]
Same problem here, but the workaround above is not available. Could you please provide some api to trigger update mannually?

**Comment by alexkatz** [comment]
Hi. I've tried to reproduce your issue here: https://codesandbox.io/s/romantic-hooks-459fo?file=/src/App.js

I can't seem to reproduce it. If you'd like, take a look and see if this solves your issue!

**Comment by crowmw** [comment]
I've probably used older version of react-tiny-popover, meybe problem were solved in newer versions

**Comment by odinho** [comment]
Yeah new version don't display this problem.

**Comment by alexkatz** [comment]
I'll close this for now. Thanks.
