### ISSUE TITLE
4.1.0 introduces a breaking change and should be revoked (and re-released as 5.0.0)

### ISSUE THREAD

**Issue by nathggns** [alexkatz/react-tiny-popover#60]
Firstly, thank you for working on this great project and providing it to us to use. 

However, 4.1.0 changes from using findDOMNode to cloning the child node and adding a ref parameter to it in order to access the dom node. Unfortunately, this is a breaking change, as any use of react tiny popover that does not directly pass a host node as a child will now be broken and be required to update their code to use forwardRef. 

If this approach of cloning the child to insert a ref is to be maintained, the release of version 4.1.0 should be revoked and relabelled as 5.0.0 as it is a breaking change. This is important, as many people have tools that automatically merge minor updates as 4.1.0 as they are not supposed to be breaking change.

Additionally, a warning should be added to the documentation that says refs need to be forwarded. It would be great to catch the error introduced when refs are not forwarded, and to make the error more descriptive too. 

![image](https://user-images.githubusercontent.com/719814/82206601-6d3d3900-9900-11ea-86ad-517359b2f07e.png)

However, I'm not sure this is actually the best approach. Using cloneElement is kind of "magic", and it is only by reading the diff of the update that I was able to figure out why 4.1.0 broke our app and how to fix it.  Two alternative approaches if you wish to use refs is to automatically wrap the child with a div, and then use `ref.current.firstChild` to access the child, or to replace the child with a render function that you pass the ref. Both of these would also likely be considered breaking changes and require a 5.0.0 moniker.

**Comment by alexkatz** [comment]
Thank you for bringing this to my attention. I'll have this version revoked and release a major version update, likely changing Popover's child to a render function injected with a ref. That pattern, although slightly more complex, seems to be the best way to replace findDOMNode's functionality without adding anything like an extra div to the DOM. I do wonder though if a better way exists.

In any case, stay tuned for that update and associated docs. Apologies for the inconvenience in the interim.

**Comment by volkandkaya** [comment]
Yep just broke my app after upgrading.

I can't use wrap children with elements.

Looking forward to the fix.

**Comment by nathggns** [comment]
@volkandkaya this *can* be addressed in userland just by wrapping your component child in a `forwardRef` and passing the ref through to the host node manually.

**Comment by alexkatz** [comment]
Correct. The fix will require passing the ref manually regardless, so any functional component used as a Popover child will now have to consume an injected ref via ref forwarding. 

This is a consequence of React phasing out the imperative nature of findDOMNode in favor of the declarative nature of refs (which I honestly approve of philosophically). I'm struggling to see if there's a way to accommodate functional components without inserting an extra div or injecting a ref to forward. I don't think there's any other proper way in Strict mode. Am I correct in this thinking?

**Comment by nathggns** [comment]
@alexkatz your problem essentially is there's no way to force a child to have a prop if the child is not properly setup to forward those props to a host node – even if you used IDs or classNames instead of refs (which I wouldn't advise), you're going to rely on the user forwarding that too. 

The only way I can think of avoiding having the user forward props (/ref) is to have a container that you control. But even that's probably a breaking change.

**Comment by volkandkaya** [comment]
If it isn't possible that is fine just have some nice docs to help people swap.

And maybe up it to 5.0.0 as @nathggns said.

**Comment by alexkatz** [comment]
Yep, stay tuned for the update and associated docs. Working on it now.

I'm bummed that findDOMNode seemed to have this unique functionality that isn't possible in Strict mode. I guess that's just the path React is taking as a framework, which ultimately I approve of. findDOMNode was a rather hacky approach to begin with that kind of violated the principles of React itself. It certainly simplified things though in this case.

**Comment by nathggns** [comment]
> I'm bummed that findDOMNode seemed to have this unique functionality that isn't possible in Strict mode. I guess that's just the path React is taking as a framework, which ultimately I approve of. findDOMNode was a rather hacky approach to begin with that kind of violated the principles of React itself. It certainly simplified things though in this case.

@alexkatz I completely get where you're coming from. I guess the React team's argument would be that this change is making what was previously an unsafe implicit requirement, safe and explicit (that there is a single host node rendered to represent the containing box to attach the popover to). If you go down the _supply the ref as a render prop_ method, then you're also giving the user the ability to specify exactly which host node to attach the popover to, rather than the implicit requirement of it being a single direct descendent.

**Comment by alexkatz** [comment]
Yup, you're right. Ultimately it's better that way, even if it makes this popover API slightly less elegant.

**Comment by alexkatz** [comment]
Version 5 is now out. Thank you guys for your patience. I'l go ahead and close this for now, but feel free to reopen if something is behaving oddly or remains unclear.

Thanks!

**Comment by odinho** [comment]
Hi @alexkatz.

I just did a minor version bump, and this broke our app. Could you please redact the `4.1.0` release since it is clearly breaking it's API? I mean it's an easy enough fix, and we'll just jump to version 5 now, -- but it is not a good practice to change API in a minor version.

If you cannot disable the 4.1.0 release on npm, maybe create a branch of the old 4.0.0 as 4.2.0 so anyone doing an minor update won't break their code like I did? :)

Thanks for your work on this!

**Comment by odinho** [comment]
Shit, it *is* deprecated, but `yarn upgrade` still upgraded to it. So yarn is the bad boy here.

**Comment by nathggns** [comment]
I think re-releasing 4.0 as 4.2 is a good idea

**Comment by odinho** [comment]
Indeed, or even `4.1.1` would work.

Yarn did print the warning, but in a huge project those are hard to see, since it scrolls out of the screen right away with other output. :)
