### ISSUE TITLE
Transition Duration Zero

### ISSUE THREAD

**Issue by jmbastidas** [alexkatz/react-tiny-popover#61]
This plugin is not supporting transition duration zero and that is causing side effects.
For example I have a set of HTML nodes, each one of them renders a [...] button, and when you click it we render popover content, when that popover is rendered then I go to another HTML block that has [...] button and then without closing the current popover I click that [...] button, what happens is that the first popover is faded out (opacity: 0) and never removed from the DOM, it is also clickable despite the user does not see it.

I managed to fix it by adding transitionDuration={0.000001} which feels like a small hack.
In the past I proposed a fix by allowing support transitionDuration=0

So I propose 2 things:

### Support zero transitionDuration

Line 264: is not taking into account when you pass 0 for transitionDuration, || in this line will ignore 0 value.
`this.removePopoverTimeout = window.setTimeout(remove, (transitionDuration || Constants.FADE_TRANSITION) * 1000); `

Suggested code change as follows:

```
        if (!this.willUnmount || transitionDuration  > 0) {
            this.removePopoverTimeout = window.setTimeout(remove, (transitionDuration || Constants.FADE_TRANSITION) * 1000);
        } else {
            remove();
        }
```

### When a popover is opened and we try to open another one, make sure the first one is really removed from the DOM (as right now DIV is the with opacity: 0):

**Opacity 0:**
`<div class="UI__Popover__popover" style="overflow: hidden; position: absolute; top: 247px; left: 234px; opacity: 0; transition: opacity 0.35s ease 0s;">`

**Visible One:**
`<div class="UI__Popover__popover" style="overflow: hidden; position: absolute; top: 247px; left: 665px; opacity: 1; transition: opacity 0.35s ease 0s;">`

**Comment by nick-tw** [comment]
Having this issue as well.

**Comment by damien916** [comment]
on my side, adding `transitionDuration={0.000001}` leads to an issue on Safari, popover is not displayed until another css transition is applied (like hover effect on another component)

**Comment by jmbastidas** [comment]
v6 does not have transition duration anymore, upgrade to that one

**Comment by colepeters** [comment]
Any action on this? Upgrading to the v6 beta isn't an option for me as it seems the positioning of the popover is broken (even after updating my custom components to forward refs).

**Comment by alexkatz** [comment]
Version 6 should solve this entirely! Closing this issue for now, but feel free to open another if you experience a similar issue with v6.
