### ISSUE TITLE
feature: support more/custom transition effect?

### ISSUE THREAD

**Issue by zhaoyao91** [alexkatz/react-tiny-popover#62]
Currently the only transition effect is opacity changing. how about support more effect or allow customization?

**Comment by sikozonpc** [comment]
In version 4.0.0 that was thing, however after upgrading to v6.0.4 it doesn't work as expected.
In my case, I had the following transition styles:

```css
transition-timing-function: cubic-bezier(0.175, 0.885, 0.32, 1.175);
transition-duration: 300ms;
transition-property: opacity, -webkit-transform, transform;
```

and actual behaviour is not as expected, the Popover would come flying from the (0,0) position on the screen to the component's position.

**Comment by alexkatz** [comment]
I've since removed the transition api entirely, and figure it's better for users to handle animations from within the popover content using whatever css or animation libraries they'd prefer. When I have time I'll try to throw together a few examples and include them in the docs.
