### ISSUE TITLE
Is there any changelog\release log?

### ISSUE THREAD

**Issue by deser** [alexkatz/react-tiny-popover#63]
You are making breaking changes to lib but it is hard to understand whether there are breaking changes or not.

**Comment by jafin** [comment]
Some things I noticed when I updated from 5 to 6 the following:

* Import declarations previously imported as default change to import explicit declaration

```ts
import Popover from 'react-tiny-popover';
```
to
```ts
import { Popover } from 'react-tiny-popover';
```

* Prop position has been replaced with positions which accepts an array of positions
```tsx
position = {'top'}
```
to
```tsx
positions = {['top']}  // preferred positions by priority
```

* property `targetRect` is no longer valid on ArrowContainer, appears it is replaced with `childRect`

Would be great to note in release notes in case the above is wrong or there are more changes.

**Comment by olaj** [comment]
disableReposition seems to have been renamed to reposition and i suppose you need to change from true -> false depending on what you had.

**Comment by alexkatz** [comment]
Hi! From version 6 and on I've added a change log to the repo and tried to be very explicit about changes, fixes, etc.. Thanks for your input!
