### ISSUE TITLE
Jest Testing Documentation

### ISSUE THREAD

**Issue by bradley-varol** [alexkatz/react-tiny-popover#68]
A co-worker and I have spent quite some time recently trying to understand why my react-testing Jest tests expecting the popover to be closed were failing. Here's what I found - it might be useful to add this stuff to the docs:

```javascript
it('should close when clicked away from', async () => {
    jest.useFakeTimers(); // necessary
    const { getByText, queryByText } = renderPopover();
    jest.runAllTimers(); // necessary

    fireEvent.click(getByText('Popover trigger'));
    expect(getByText('Popover content.')).toBeDefined();

    fireEvent.click(getByText('Element outside of the popover trigger'));
    jest.runOnlyPendingTimers(); // necessary
    expect(queryByText('Popover content.')).toBeNull();
});
```
I believe the Jest fake timers are necessary because of some `setTimeout` calls in the code of this library.
It's also worth mentioning that the react-testing `waitForElementToBeRemoved` method doesn't work with this library hence this:
```javascript
jest.runOnlyPendingTimers();
expect(queryByText('Popover content.')).toBeNull();
```
I also found that the `windowBorderPadding` must be set to `0`, otherwise the popover gets re-positioned, failing my tests.

**Comment by themagickoala** [comment]
I am the co-worker mentioned above, and we've been looking into this further. I can share some more info here after further investigation.

We opted to use jest's fakeTimers here to have fine-grained control over managing the timeouts and intervals used in this library, however there seem to be some inconsistencies/race conditions occurring. With @bradley-varol's sample code above, we were still getting intermittent errors, and the only way we've found to resolve them is to use `jest.runAllTimers()` after every fireEvent to flush everything out.

So far this has resolved our intermittent test failures, but it's not ideal. Could you shed more light onto how you've tested this internally? It'd be really helpful if the repository included your own testing system.

**Comment by themagickoala** [comment]
Nevermind, got another test failure in our CI server, so even runAllTimers doesn't resolve this. To be clear, we are doing the following (simplified a little for brevity):

```javascript
it('should show and hide a popover'. () => {
    jest.useFakeTimers();
    render(<Popover/>);
    jest.runAllTimers(); // to ensure that willMount gets set to false;

    fireEvent.mouseEnter(triggerElement);
    jest.runAllTimers(); // latest test failure ran 100000 timers with more still to go

    expect(popoverContentElement).toBeDefined();

    fireEvent.mouseLeave(triggerElement);
    jest.runAllTimers();

    expect(popoverContent).toBeNull();
});
```

We've tried a few variations on this, like `runOnlyPendingTimers()` but the popover content isn't removed from the DOM with this. The same is true with `advanceTimersByTime(1000)`, which is more than the timeout that should be needed for the popover to fade out and be removed. Is it possible that you have a memory leak in your timeouts/intervals?

**Comment by alexkatz** [comment]
@bradley-varol, @themagickoala, I've released a version 6, which no longer relies on `setTimeout` at all. Give that a shot if you'd like. It's entirely functional and hooks based. 

I'll close this issue for now, but if you end up upgrading, let me know!
