### ISSUE TITLE
Element is stay at DOM while popover is closed

### ISSUE THREAD

**Issue by emreesirik** [alexkatz/react-tiny-popover#69]
<img width="1792" alt="Screen Shot 2020-06-24 at 09 54 03" src="https://user-images.githubusercontent.com/7847917/85522958-fdad1e80-b60e-11ea-9564-058f33eb63fc.png">

We are using popover as a tooltip. While hover on list that each element has a tooltip, sometimes popover elements are not clean from dom. 

There are code sample. https://codesandbox.io/s/react-tiny-popover-demo-hbs9z?file=/src/index.js

I think there is a problem about hide with transition. because when I close to `if (!this.willUnmount)` block  in removePopover() method  Popover.tsx class, this bug is fixed. But I couldn't find work correctly when hide with transition.
 
`	private removePopover() {
		// this should now be a callback to handle event listening upon portal disappearance
		const { /* transitionDuration, */ isOpen } = this.props

		if (this.popoverDiv) {
			this.popoverDiv.style.opacity = "0"
		}

		const remove = () => {
			if (this.willUnmount || !isOpen || !this.popoverDiv.parentNode) {
				window.clearInterval(this.targetPositionIntervalHandler)
				window.removeEventListener("resize", this.onResize)
				window.removeEventListener("click", this.onClick)
				//@ts-ignore
				this.targetPositionIntervalHandler = undefined
				this.setState({ isTransitioningToClosed: false })
			}
		}
		/* 	if (!this.willUnmount) {
			this.removePopoverTimeout = window.setTimeout(
				remove,
				(transitionDuration || Constants.FADE_TRANSITION) * 1000,
			)
		} else { */
		remove()
		/* } */
	}`

**Comment by acfasj** [comment]
came across the same problem

**Comment by jmbastidas** [comment]
Same thing, same problem, see: https://github.com/alexkatz/react-tiny-popover/issues/61
Maybe supporting zero transition duration will fix it.
When transitionDuration was introduced we started to experience this problem.

The problem:
Sometimes window.setTimeout does not work, something cancels it, so remove is sometimes not called.

**Comment by roeibit** [comment]
same issue here.

**Comment by roeibit** [comment]
Just noticed that setting "transitionDuration={-1}" fixes the issue for me

**Comment by FlorianWendelborn** [comment]
Seems to only happen when scrolling at the same time.

**Comment by manuatbestmile** [comment]
+1

**Comment by ever-dev** [comment]
Same issue here

**Comment by ever-dev** [comment]
Just found a solution but not perfect.

```
const [visible, setVisible] = useState(false);
  return (
    <Popover
      content={() => (
        <div css={styles.popup} onClick={e => e.stopPropagation()}>
          {visible && (
            <Content
              closePopup={() => {
                setVisible(false);
                onVisibleChange && onVisibleChange(false);
              }}
            />
          )}
        </div>
      )}
      isOpen={visible}
      onClickOutside={() => {
        hideOnOutsideClick && setVisible(false);
        onVisibleChange && onVisibleChange(false);
      }}
      padding={padding}
      position={position}
      align={align}
    >
      <div
        onClick={() => {
          onVisibleChange && onVisibleChange(!visible);
          setVisible(!visible);
        }}
      >
        {children}
      </div>
    </Popover>
  );
```

**Comment by alexkatz** [comment]
Should be fixed in v6. Here's that same codesandbox updated to v6.0.1.  

https://codesandbox.io/s/react-tiny-popover-demo-forked-v7h0n?file=/src/index.js

Closing for now. However, please let me know if you still experience this issue. Thanks guys!
