### ISSUE TITLE
Meta: Could you add a tag on every release?

### ISSUE THREAD

**Issue by odinho** [alexkatz/react-tiny-popover#72]
Trying to figure out what changed between the 5.0.0 and the 5.1.0 release. This is a place where I usually check the "GitHub releases" page, or just check the tags.

Doing a tag can be as easy as `git tag 5.1.0; git push --tags`, but will be very helpful when looking at the commits backwards to see what release correspond to what tag. It's even nicer when projects also write a bit about each release, what changes went in etc, but this is not required IMHO for such a small project, it's easy enough just to read the commit subjects, and the linked PRs and the code.

Thanks! (You can do this retroactively for a few releases to back-fill some handy data).

**Comment by alexkatz** [comment]
Will do, thanks for the heads up.
