### ISSUE TITLE
content ({ popoverReact }) scroll calc issue

### ISSUE THREAD

**Issue by dexterns88** [alexkatz/react-tiny-popover#84]
When we use content function like example
```
content={({ position, targetRect, popoverRect }) => (
    <ArrowContainer // if you'd like an arrow, you can import the ArrowContainer!
      position={position}
      targetRect={targetRect}
      popoverRect={popoverRect}
      arrowColor={'blue'}
      arrowSize={10}
      arrowStyle={{ opacity: 0.7 }}
    >
```

When scrolling browser object `popoverRect` return all zero value
```
{
  "top": 0,
  "left": 0,
  "bottom": 0,
  "height": 0,
  "right": 0,
  "width": 0
}
```
`height` and `width` of content is not changed while scrolling, we don't need to zero that value.
We using `popoverRect` width and height to calculate arrow position, and they changing position when scrolling because content dimension return 0.

**Comment by alexkatz** [comment]
Closing this as I believe it's been fixed since, but please open another issue if you're still experiencing this by any chance.
