### ISSUE TITLE
Simple example code not working - "Element type is invalid: expected a string (for built-in components) or a class/function..."

### ISSUE THREAD

**Issue by jameschetwood** [alexkatz/react-tiny-popover#85]
`Yarn install` adds version 6.0.0-beta.2 but this doenst work with the simple example in the readme:

```
const App = () => {
  return (
    <div>
      <h1>hi</h1>
      <Popover
        isOpen={true}
        position={"top"}
        content={<p>Hi! I'm popover content.</p>}
      >
        <p>Click me!</p>
      </Popover>
    </div>
  );
};
```

https://codesandbox.io/s/currying-monad-vfe5t?file=/package.json

**Comment by robbienohra** [comment]
I've started getting this issue with the latest version as well

**Comment by robbienohra** [comment]
@jameschetwood I think I've figured out the issue

It looks like the way you import the component has changed with the latest version from:

`import Popover from 'react-tiny-popover'`

to

`import { Popover } from 'react-tiny-popover'`

Looks like de-structuring is now required

**Comment by alexkatz** [comment]
I've released v6, and updated the docs. Hopefully things are once again clear. Closing this for now, but feel free to bring other issues to my attention if you encounter any.
