### ISSUE TITLE
Popover position not respected in version 6

### ISSUE THREAD

**Issue by colepeters** [alexkatz/react-tiny-popover#89]
I've just tried updating to version 6 of this library to try and get around the issue described in #61 (the Popover content remains in the DOM though it's visually hidden), and have found that the `position` prop passed to Popover is not being respected. In my app I'm passing an array of `['bottom', 'top']` but it's always rendering on top.

I've reproduced the issue in this Codesandbox using just the string `'bottom'` to demontrate: https://codesandbox.io/s/blue-butterfly-l75w4?file=/src/App.js

**Comment by colepeters** [comment]
On further investigation, it looks like the prop `position` has been changed (or typo'd? 😅) to `positions`: https://github.com/alexkatz/react-tiny-popover/blob/master/src/Popover.tsx#L30

I tried changing my Popover component to use `positions` instead of `position` and that resolved the issue. Not sure if this intentional, though!

**Comment by alexkatz** [comment]
Yep, that’s right. Version 6 is still in beta, though I’m planning on updating the docs, demo, and releasing 6.0 shortly.

Thanks for your patience in the meantime!

**Comment by colepeters** [comment]
Oh wow, I totally missed that v6 was still in beta. Thank you!

**Comment by alexkatz** [comment]
Finally updated the docs and released v6. I'll close this for now, but if you experience any further issues, don't hesitate to let me know!

**Comment by colepeters** [comment]
Thanks for your work on this @alexkatz!

**Comment by colepeters** [comment]
Sorry @alexkatz, but I think I'm missing something? The documentation on the repo's readme still seems to be outdated (doesn't show the need to import the named `Popover`, `positions` is still shown as `position`…). Are the updated docs somewhere else…?

**Comment by alexkatz** [comment]
Thanks for pointing that out. Should now be fixed.

**Comment by colepeters** [comment]
Ahh, there we go. Thanks again!
