### ISSUE TITLE
childRef.current is undefined during unmount

### ISSUE THREAD

**Issue by shrugs** [alexkatz/react-tiny-popover#90]
Whenever my tiny popover is unmounted, it attempts to access `childRef.current` on this line https://github.com/alexkatz/react-tiny-popover/blob/471d7519d93ca7c88332ba9386f65aa00b33ce0c/src/Popover.tsx#L79 which I assume is a race condition between react removing the component from the dom and the callback being run in the request animation frame.

a simple solution is to check for the existence of the ref before operating on it, since we can assume that if the ref is undefined, there's nothing to update

https://github.com/alexkatz/react-tiny-popover/blob/471d7519d93ca7c88332ba9386f65aa00b33ce0c/src/Popover.tsx#L78

`if (isOpen && childRef.current)`

**Comment by alexkatz** [comment]
Should be fixed in the latest version!
