### ISSUE TITLE
positioning defaults to 0, 0 initially after updating to v6.0.1 

### ISSUE THREAD

**Issue by shrugs** [alexkatz/react-tiny-popover#92]
perhaps due to this change? uncertain. https://github.com/alexkatz/react-tiny-popover/commit/7166d46a8966ce3986f6122efcf4e74449ef9c45#diff-1cfbedd17398bf061869f817161454f8e0e3b1fc3c9ea04173bb1b11f475c726R51

notice how the popover starts at the top left for a frame, then gets repositioned correctly. it does remember its position when opened a second time

![Untitled](https://user-images.githubusercontent.com/1535001/101658387-f8079180-3a12-11eb-9414-097c3c3a8e7e.gif)

**Comment by jlevy-io** [comment]
Been banging my head against this all morning

**Comment by alexkatz** [comment]
Ah, thanks, yeah I do notice this.

One quick fix you can do for now is set the popover container's transition to none, as shown here:

https://codesandbox.io/s/condescending-edison-s4zwt?file=/src/App.js

Perhaps I should leave transition off of the popover container by default, and I'll have to take a look at that 0, 0 issue. Thanks for bringing this to my attention!

**Comment by jlevy-io** [comment]
@alexkatz Thanks, that worked great!

**Comment by alexkatz** [comment]
In the 6.0.2 update now released, this problem should no longer exist. The fix in the codesandbox above is no longer necessary.

Thanks!
