### ISSUE TITLE
Popover is animating in from top left of viewport

### ISSUE THREAD

**Issue by colepeters** [alexkatz/react-tiny-popover#93]
As of 6.0.1 (not sure if earlier), Popovers are translating into position from the top left corner of the viewport. See this repro (tested on Chrome and Safari): https://codesandbox.io/s/blue-butterfly-l75w4

**Edit:** This only happens the first time a popover is triggered.

Expected behaviour: they should not be animating into place from the top left corner 😅

**Comment by alexkatz** [comment]
Here's a quick fix for now: https://codesandbox.io/s/condescending-edison-s4zwt?file=/src/App.js

In that codesandbox, I've disabled the css transition that I've placed by default on the popover container. 

In the next release, I'll likely remove the default css transition altogether, and leave that up to users to implement themselves through the `containerStyle` prop.

Stay tuned for that. Hopefully this fix solves the problem for now, though.

**Comment by colepeters** [comment]
Awesome, thank you for the quick follow up!

**Comment by alexkatz** [comment]
@colepeters, I've pushed 6.0.2. Should fix the issue altogether! The fix in the codesandbox above should no longer be necessary.

**Comment by colepeters** [comment]
So fast! Thanks again!
